### PR TITLE
Cond_size bug fix

### PR DESCRIPTION
**Pull request by shoaibahmed**
Bug fixed in cond_size computation

### CODE REVIEW

**Comment by wannesm** [comment]
Both versions seem identical to me (assuming the division operator in Python 3). Or am I missing something?

**Comment by soumenms2015** [comment]
This version was generating an error in Python3, therefore, this change was necessary.

**Comment by wannesm** [comment]
Thanks for the additional information. Can you provide an example?

**Comment by shoaibahmed** [comment]
This image provides a glimpse of the issue with Python3 due to inconsistency in division between the two Python versions. The result should be 496 while the current code returns 495.
image

**Comment by wannesm** [comment]
This is indeed a problem with the stability of the division. The numbers returned by the factorial are too large and trigger numerical problems. Since this method is also unnecessarily inefficient, we replaced it with a simpler formula when we moved clustering to the library last year. Since the example file ``examples/hierarchical_clustering.py`` is not relevant anymore, I have removed the file. See the ``dtaidistance/clustering.py`` file for the most recent implementation.

**Pull request closed without merging**
